# Generated by Django 6.0.6 on 2026-06-10 11:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pid', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='public id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(max_length=255, verbose_name='short name')),
                ('abbreviation', models.CharField(max_length=8, verbose_name='abbreviation')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='city')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='crest colour')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pid', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='public id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='squad number')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2, verbose_name='position')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/', verbose_name='photo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ['team', 'number', 'name'],
            },
        ),
    ]
