# Generated by Django 6.0.6 on 2026-06-10 11:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pid', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='public id')),
                ('competition', models.CharField(blank=True, max_length=255, verbose_name='competition')),
                ('round', models.CharField(blank=True, max_length=255, verbose_name='round')),
                ('venue', models.CharField(blank=True, max_length=255, verbose_name='venue')),
                ('kickoff_at', models.DateTimeField(blank=True, null=True, verbose_name='kickoff at')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished')], default='SCHEDULED', max_length=10, verbose_name='status')),
                ('minute', models.PositiveSmallIntegerField(default=0, verbose_name='minute')),
                ('home_score', models.PositiveSmallIntegerField(default=0, verbose_name='home score')),
                ('away_score', models.PositiveSmallIntegerField(default=0, verbose_name='away score')),
                ('home_formation', models.CharField(default='4-3-3', max_length=10, verbose_name='home formation')),
                ('away_formation', models.CharField(default='4-3-3', max_length=10, verbose_name='away formation')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='teams.team', verbose_name='away team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='teams.team', verbose_name='home team')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'ordering': ['-kickoff_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pid', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='public id')),
                ('side', models.CharField(blank=True, choices=[('HOME', 'Home'), ('AWAY', 'Away')], max_length=4, null=True, verbose_name='side')),
                ('type', models.CharField(choices=[('GOAL', 'Goal'), ('PENALTY', 'Penalty'), ('YELLOW', 'Yellow card'), ('RED', 'Red card'), ('SUB', 'Substitution'), ('CHANCE', 'Chance'), ('CORNER', 'Corner'), ('FOUL', 'Foul'), ('VAR', 'VAR'), ('WHISTLE', 'Whistle')], max_length=10, verbose_name='type')),
                ('minute', models.PositiveSmallIntegerField(default=0, verbose_name='minute')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='commentary')),
                ('is_major', models.BooleanField(default=False, verbose_name='major')),
                ('primary_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.player', verbose_name='primary player')),
                ('secondary_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.player', verbose_name='secondary player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-minute', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PlayerPositionInMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pid', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='public id')),
                ('role', models.CharField(choices=[('STARTER', 'Starter'), ('SUBSTITUTE', 'Substitute')], max_length=10, verbose_name='role')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2, verbose_name='position')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_positions', to='matches.match', verbose_name='match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.player', verbose_name='player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'player position',
                'verbose_name_plural': 'player positions',
                'ordering': ['match', 'team', 'role', 'order'],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_player_position_per_match')],
            },
        ),
        migrations.CreateModel(
            name='TeamStatsInMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pid', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='public id')),
                ('possession', models.PositiveSmallIntegerField(default=0, verbose_name='possession %')),
                ('total_shots', models.PositiveSmallIntegerField(default=0, verbose_name='total shots')),
                ('shots_on_target', models.PositiveSmallIntegerField(default=0, verbose_name='shots on target')),
                ('corners', models.PositiveSmallIntegerField(default=0, verbose_name='corners')),
                ('fouls', models.PositiveSmallIntegerField(default=0, verbose_name='fouls')),
                ('offsides', models.PositiveSmallIntegerField(default=0, verbose_name='offsides')),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0, verbose_name='yellow cards')),
                ('red_cards', models.PositiveSmallIntegerField(default=0, verbose_name='red cards')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='matches.match', verbose_name='match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'team stats',
                'verbose_name_plural': 'team stats',
                'ordering': ['match', 'team'],
                'constraints': [models.UniqueConstraint(fields=('match', 'team'), name='unique_team_stats_per_match')],
            },
        ),
    ]
