# Generated by Django 6.0.6 on 2026-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='away penalty score'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='home penalty score'),
        ),
    ]
