# Generated by Django 6.0.6 on 2026-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_penalty_score_match_home_penalty_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='minute',
        ),
        migrations.AddField(
            model_name='match',
            name='clock_elapsed_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='clock elapsed seconds'),
        ),
        migrations.AddField(
            model_name='match',
            name='clock_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='clock started at'),
        ),
    ]
